spring.application.name=gestion-academica
server.port=${PORT:8080}

#URL de conexión (le agregué cambié lo del "jdbc:" ya que como va a estar subido a render usa otro)
spring.datasource.url=${DB_URL}
#Usuario :D
spring.datasource.username=${DB_USER}
#contraseña del supabase :D
spring.datasource.password=${DB_PASSWORD}

#Configuraciones para que Spring hable bien con PostgreSQL y Supabase
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5